; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
[platformio]
build_dir = C:/pio_build/Final_Project

[env:esp32dev]
platform = espressif32
board = esp32dev
; board_build.partitions = era_partition.csv
board_build.filesystem = spiffs
framework = arduino
monitor_speed = 115200
lib_deps = 
  bodmer/TFT_eSPI @ ^2.5.43
  bodmer/TJpg_Decoder @ ^1.1.0
  https://github.com/mobizt/Firebase-ESP-Client.git
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3


build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=21
  -D TFT_RST=22
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SMOOTH_FONT=1
upload_speed = 115200
